//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doCommandRequest
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.inf.hexing.cn", ConfigurationName="doCommandRequest.DoCommandRequest")]
    public interface DoCommandRequest
    {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento arg0 do namespace  não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/doCommand", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/doCommandResponse")]
        doCommandRequest.doCommandResponse doCommand(doCommandRequest.doCommand request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/doCommand", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/doCommandResponse")]
        System.Threading.Tasks.Task<doCommandRequest.doCommandResponse> doCommandAsync(doCommandRequest.doCommand request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento arg0 do namespace  não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/compress", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/compressResponse")]
        doCommandRequest.compressResponse compress(doCommandRequest.compress request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/compress", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/compressResponse")]
        System.Threading.Tasks.Task<doCommandRequest.compressResponse> compressAsync(doCommandRequest.compress request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento arg0 do namespace  não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/getResponse", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/getResponseResponse")]
        doCommandRequest.getResponseResponse getResponse(doCommandRequest.getResponse request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/getResponse", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/getResponseResponse")]
        System.Threading.Tasks.Task<doCommandRequest.getResponseResponse> getResponseAsync(doCommandRequest.getResponse request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento arg0 do namespace  não está marcado como anulável
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/uncompress", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/uncompressResponse")]
        doCommandRequest.uncompressResponse uncompress(doCommandRequest.uncompress request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.inf.hexing.cn/DoCommandRequest/uncompress", ReplyAction="http://soap.inf.hexing.cn/DoCommandRequest/uncompressResponse")]
        System.Threading.Tasks.Task<doCommandRequest.uncompressResponse> uncompressAsync(doCommandRequest.uncompress request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCommand
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCommand", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.doCommandBody Body;
        
        public doCommand()
        {
        }
        
        public doCommand(doCommandRequest.doCommandBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class doCommandBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public doCommandBody()
        {
        }
        
        public doCommandBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCommandResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCommandResponse", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.doCommandResponseBody Body;
        
        public doCommandResponse()
        {
        }
        
        public doCommandResponse(doCommandRequest.doCommandResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class doCommandResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public doCommandResponseBody()
        {
        }
        
        public doCommandResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compress
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compress", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.compressBody Body;
        
        public compress()
        {
        }
        
        public compress(doCommandRequest.compressBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class compressBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public compressBody()
        {
        }
        
        public compressBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compressResponse", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.compressResponseBody Body;
        
        public compressResponse()
        {
        }
        
        public compressResponse(doCommandRequest.compressResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class compressResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public compressResponseBody()
        {
        }
        
        public compressResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResponse", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.getResponseBody Body;
        
        public getResponse()
        {
        }
        
        public getResponse(doCommandRequest.getResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getResponseBody()
        {
        }
        
        public getResponseBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResponseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResponseResponse", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.getResponseResponseBody Body;
        
        public getResponseResponse()
        {
        }
        
        public getResponseResponse(doCommandRequest.getResponseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResponseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getResponseResponseBody()
        {
        }
        
        public getResponseResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uncompress
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uncompress", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.uncompressBody Body;
        
        public uncompress()
        {
        }
        
        public uncompress(doCommandRequest.uncompressBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uncompressBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public uncompressBody()
        {
        }
        
        public uncompressBody(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uncompressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="uncompressResponse", Namespace="http://soap.inf.hexing.cn", Order=0)]
        public doCommandRequest.uncompressResponseBody Body;
        
        public uncompressResponse()
        {
        }
        
        public uncompressResponse(doCommandRequest.uncompressResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class uncompressResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public uncompressResponseBody()
        {
        }
        
        public uncompressResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface DoCommandRequestChannel : doCommandRequest.DoCommandRequest, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class DoCommandRequestClient : System.ServiceModel.ClientBase<doCommandRequest.DoCommandRequest>, doCommandRequest.DoCommandRequest
    {
        
        public DoCommandRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doCommandRequest.doCommandResponse doCommandRequest.DoCommandRequest.doCommand(doCommandRequest.doCommand request)
        {
            return base.Channel.doCommand(request);
        }
        
        public string doCommand(string arg0)
        {
            doCommandRequest.doCommand inValue = new doCommandRequest.doCommand();
            inValue.Body = new doCommandRequest.doCommandBody();
            inValue.Body.arg0 = arg0;
            doCommandRequest.doCommandResponse retVal = ((doCommandRequest.DoCommandRequest)(this)).doCommand(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doCommandRequest.doCommandResponse> doCommandRequest.DoCommandRequest.doCommandAsync(doCommandRequest.doCommand request)
        {
            return base.Channel.doCommandAsync(request);
        }
        
        public System.Threading.Tasks.Task<doCommandRequest.doCommandResponse> doCommandAsync(string arg0)
        {
            doCommandRequest.doCommand inValue = new doCommandRequest.doCommand();
            inValue.Body = new doCommandRequest.doCommandBody();
            inValue.Body.arg0 = arg0;
            return ((doCommandRequest.DoCommandRequest)(this)).doCommandAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doCommandRequest.compressResponse doCommandRequest.DoCommandRequest.compress(doCommandRequest.compress request)
        {
            return base.Channel.compress(request);
        }
        
        public string compress(string arg0)
        {
            doCommandRequest.compress inValue = new doCommandRequest.compress();
            inValue.Body = new doCommandRequest.compressBody();
            inValue.Body.arg0 = arg0;
            doCommandRequest.compressResponse retVal = ((doCommandRequest.DoCommandRequest)(this)).compress(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doCommandRequest.compressResponse> doCommandRequest.DoCommandRequest.compressAsync(doCommandRequest.compress request)
        {
            return base.Channel.compressAsync(request);
        }
        
        public System.Threading.Tasks.Task<doCommandRequest.compressResponse> compressAsync(string arg0)
        {
            doCommandRequest.compress inValue = new doCommandRequest.compress();
            inValue.Body = new doCommandRequest.compressBody();
            inValue.Body.arg0 = arg0;
            return ((doCommandRequest.DoCommandRequest)(this)).compressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doCommandRequest.getResponseResponse doCommandRequest.DoCommandRequest.getResponse(doCommandRequest.getResponse request)
        {
            return base.Channel.getResponse(request);
        }
        
        public string getResponse(string arg0)
        {
            doCommandRequest.getResponse inValue = new doCommandRequest.getResponse();
            inValue.Body = new doCommandRequest.getResponseBody();
            inValue.Body.arg0 = arg0;
            doCommandRequest.getResponseResponse retVal = ((doCommandRequest.DoCommandRequest)(this)).getResponse(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doCommandRequest.getResponseResponse> doCommandRequest.DoCommandRequest.getResponseAsync(doCommandRequest.getResponse request)
        {
            return base.Channel.getResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<doCommandRequest.getResponseResponse> getResponseAsync(string arg0)
        {
            doCommandRequest.getResponse inValue = new doCommandRequest.getResponse();
            inValue.Body = new doCommandRequest.getResponseBody();
            inValue.Body.arg0 = arg0;
            return ((doCommandRequest.DoCommandRequest)(this)).getResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doCommandRequest.uncompressResponse doCommandRequest.DoCommandRequest.uncompress(doCommandRequest.uncompress request)
        {
            return base.Channel.uncompress(request);
        }
        
        public string uncompress(string arg0)
        {
            doCommandRequest.uncompress inValue = new doCommandRequest.uncompress();
            inValue.Body = new doCommandRequest.uncompressBody();
            inValue.Body.arg0 = arg0;
            doCommandRequest.uncompressResponse retVal = ((doCommandRequest.DoCommandRequest)(this)).uncompress(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doCommandRequest.uncompressResponse> doCommandRequest.DoCommandRequest.uncompressAsync(doCommandRequest.uncompress request)
        {
            return base.Channel.uncompressAsync(request);
        }
        
        public System.Threading.Tasks.Task<doCommandRequest.uncompressResponse> uncompressAsync(string arg0)
        {
            doCommandRequest.uncompress inValue = new doCommandRequest.uncompress();
            inValue.Body = new doCommandRequest.uncompressBody();
            inValue.Body.arg0 = arg0;
            return ((doCommandRequest.DoCommandRequest)(this)).uncompressAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
